# git-related: aliases
alias changes="git status -vv | less -r"
alias gaa="git add --all"
alias gac="git add --all && git commit --verbose"
alias gai="git add --interactive"
alias gane="git commit --amend --no-edit"
alias gb="git branch -avv"
alias gcp="git cherry-pick"
alias gmt="git mergetool"
alias gs="git status"
alias gsf="git fetch && git status"
alias grc="git rebase --continue"
alias grs="git rebase --skip"
alias sle="git config --local user.email pieter.bryon@aug-e.io && git config --local --list"
