# git-related: aliases
alias changes="git status -vv | less -r"
alias gaa="git add --all"
alias gac="git add --all && git commit -v"
alias gai="git add --interactive"
alias gb="git branch -avv"
alias gcp="git cherry-pick"
alias gs="git status"
alias gsf="git fetch && git status"
alias grc="git rebase --continue"
alias grs="git rebase --skip"
